### ISSUE TITLE
ZeroTrust - The _executeClaim function will revert if the RewardPoolType is _UNUSED.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-leveraged-vaults-judging#45]
ZeroTrust

High

# The _executeClaim function will revert if the RewardPoolType is _UNUSED.

## Summary
The _executeClaim function will revert if the RewardPoolType is _UNUSED.
## Vulnerability Detail
The _executeClaim function is used for Account Claim Mode. Howerve _executeClaim will be called by _claimVaultRewards which is called by _claimAccountRewards, When user claim his Account Rewards. 
In Emission Rate Mode: poolType will be set to _UNUSED,rewardPool will be set to address(0)
Then The _executeClaim function will revert, result in claim  Account Rewards revert.

```javascript
 function _executeClaim(RewardPoolStorage memory r) internal {
        if (r.poolType == RewardPoolType.AURA) {
            require(IAuraRewardPool(r.rewardPool).getReward(address(this), true));
        } else if (r.poolType == RewardPoolType.CONVEX_MAINNET) {
            require(IConvexRewardPool(r.rewardPool).getReward(address(this), true));
        } else if (r.poolType == RewardPoolType.CONVEX_ARBITRUM) {
            IConvexRewardPoolArbitrum(r.rewardPool).getReward(address(this));
        } else {
@>            revert();
        }
    }
```
## Impact
Contract functionality DoS
## Code Snippet
https://github.com/sherlock-audit/2024-06-leveraged-vaults/blob/14d3eaf0445c251c52c86ce88a84a3f5b9dfad94/leveraged-vaults-private/contracts/vaults/common/VaultRewarderLib.sol#L181
## Tool used

Manual Review

## Recommendation
```diff
 function _executeClaim(RewardPoolStorage memory r) internal {
        if (r.poolType == RewardPoolType.AURA) {
            require(IAuraRewardPool(r.rewardPool).getReward(address(this), true));
        } else if (r.poolType == RewardPoolType.CONVEX_MAINNET) {
            require(IConvexRewardPool(r.rewardPool).getReward(address(this), true));
        } else if (r.poolType == RewardPoolType.CONVEX_ARBITRUM) {
            IConvexRewardPoolArbitrum(r.rewardPool).getReward(address(this));
        } else {
-           revert();
+           return;
        }
    }
```

**Comment by 0502lian** [comment]
Escalate
This should be considered a valid issue.
```javascript
enum RewardPoolType {
    _UNUSED,
    AURA,
    CONVEX_MAINNET,
    CONVEX_ARBITRUM
}
```
In Emission Rate Mode: poolType will be set to _UNUSED,rewardPool will be set to address(0);
In Account Claim Mode: poolType will be set to AURA, CONVEX_MAINNET or CONVEX_ARBITRUM;

because it is not a problem caused by incorrect configuration by the administrator, but rather, even with correct configuration, it would cause all users to be unable to receive rewards (in the case of being in Emission Rate Mode).

**Comment by sherlock-admin3** [comment]
> Escalate
> This should be considered a valid issue.
> ```javascript
> enum RewardPoolType {
>     _UNUSED,
>     AURA,
>     CONVEX_MAINNET,
>     CONVEX_ARBITRUM
> }
> ```
> In Emission Rate Mode: poolType will be set to _UNUSED,rewardPool will be set to address(0);
> In Account Claim Mode: poolType will be set to AURA, CONVEX_MAINNET or CONVEX_ARBITRUM;
> 
> because it is not a problem caused by incorrect configuration by the administrator, but rather, even with correct configuration, it would cause all users to be unable to receive rewards (in the case of being in Emission Rate Mode).

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
> Escalate This should be considered a valid issue.
> 
> ```js
> enum RewardPoolType {
>     _UNUSED,
>     AURA,
>     CONVEX_MAINNET,
>     CONVEX_ARBITRUM
> }
> ```
> 
> In Emission Rate Mode: poolType will be set to _UNUSED,rewardPool will be set to address(0); In Account Claim Mode: poolType will be set to AURA, CONVEX_MAINNET or CONVEX_ARBITRUM;
> 
> because it is not a problem caused by incorrect configuration by the administrator, but rather, even with correct configuration, it would cause all users to be unable to receive rewards (in the case of being in Emission Rate Mode).

If set to _UNUSED (address(0)) as you said, there's no reward to claim then. What's the impact of reverting _executeClaim() vs returning it?

**Comment by 0502lian** [comment]
> > Escalate This should be considered a valid issue.
> > ```js
> > enum RewardPoolType {
> >     _UNUSED,
> >     AURA,
> >     CONVEX_MAINNET,
> >     CONVEX_ARBITRUM
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In Emission Rate Mode: poolType will be set to _UNUSED,rewardPool will be set to address(0); In Account Claim Mode: poolType will be set to AURA, CONVEX_MAINNET or CONVEX_ARBITRUM;
> > because it is not a problem caused by incorrect configuration by the administrator, but rather, even with correct configuration, it would cause all users to be unable to receive rewards (in the case of being in Emission Rate Mode).
> 
> If set to _UNUSED (address(0)) as you said, there's no reward to claim then. What's the impact of reverting _executeClaim() vs returning it?



Please check the relevant descriptions in DOC:
https://docs.google.com/document/d/1gWFOt9m3fwFGMHk5TxPOf8KkY1ONqY9N1wPKT02ZJfI/edit

“Emission Rate: in addition to allowing claimed incentives from booster protocols, the vault may also be incentivized directly using the emissionRatePerYear setting. In this setting, incentive tokens (i.e. ARB) would be transferred directly to the vault and some emissionRate and endTime would be specified. Vault users would claim their share of these incentives over time.”

**In Emission Rate Mode, it is not that there are no rewards, but rather that the protocol does not need to go to a third-party protocol to claim the rewards.**

Users still have to call claimAccountRewards(), and then call

_claimAccountRewards() -> _claimVaultRewards() -> _executeClaim(rewardPool)

All the functions are in VaultRewarderLib.sol. You can check it, or ask the sponsor to take a look, and they will understand.
https://github.com/sherlock-audit/2024-06-leveraged-vaults/blob/14d3eaf0445c251c52c86ce88a84a3f5b9dfad94/leveraged-vaults-private/contracts/vaults/common/VaultRewarderLib.sol

In addition, I would like to add that a Vault does not have only one reward mode; it can have multiple modes. However, for a specific reward token, there is only one mode.

**Comment by T-Woodward** [comment]
@sbuljac could you take a look at this one ^

**Comment by T-Woodward** [comment]
I dispute this finding. We don't have vaults where the rewardPool is the zero address. It is correct that the current code does not work if we want to support a special pool that does not have any type of gauge, but in that situation we would add a new RewardPoolType to handle it.

**Comment by 0502lian** [comment]
> I dispute this finding. We don't have vaults where the rewardPool is the zero address. It is correct that the current code does not work if we want to support a special pool that does not have any type of gauge, but in that situation we would add a new RewardPoolType to handle it.



So you mean _UNUSED is not used for Emission Rate Mode? Which type is used for Emission Rate Mode then? Do you mean you would add a new RewardPoolType to handle it?
```javascript
enum RewardPoolType {
    _UNUSED,
    AURA,
    CONVEX_MAINNET,
    CONVEX_ARBITRUM
}

 function _executeClaim(RewardPoolStorage memory r) internal {
        if (r.poolType == RewardPoolType.AURA) {
            require(IAuraRewardPool(r.rewardPool).getReward(address(this), true));
        } else if (r.poolType == RewardPoolType.CONVEX_MAINNET) {
            require(IConvexRewardPool(r.rewardPool).getReward(address(this), true));
        } else if (r.poolType == RewardPoolType.CONVEX_ARBITRUM) {
            IConvexRewardPoolArbitrum(r.rewardPool).getReward(address(this));
        } else {
-           revert();
+           return;
        }
    }
```

**Given that the current code cannot handle the important functionality of Emission Rate Mode(that does not have any type of gauge), this should at least be considered a medium-severity issue.**

Because in Doc： https://docs.google.com/document/d/1gWFOt9m3fwFGMHk5TxPOf8KkY1ONqY9N1wPKT02ZJfI/edit

The VaultRewarderLib is meant to be an extension that allows for more flexibility when dealing with incentives. There are three potential treatments for incentive tokens:

- 1 Automatic Reinvest: this is the default mode for an incentive tokens. Tokens are claimed onto the vault and a whitelisted REWARDER_ROLE will trade the incentives and increase the total LP tokens held by all users in the vault. If an incentive token is not explicitly whitelisted by `updateRewardToken` then it will be in Automatic Reinvest mode.
- 2 Account Claim: governance will call `updateRewardToken` and whitelist an incentive token with an emissionRatePerYear set to zero. Once the incentive token is listed it cannot be removed and will no longer be in Automatic Reinvest mode. From this point forward, whenever an account enters, exits or manually claims rewards an accumulator will be used to determine how many incentive tokens an account has a claim on. There is a setting in StrategyVaultSettings called “forceClaimAfter” which can be used to limit the frequency of claims on mainnet where gas costs can be significant. An account can always bypass this check by calling `claimRewardTokens` prior to exiting.
- 3 Emission Rate: in addition to allowing claimed incentives from booster protocols, the vault may also be incentivized directly using the emissionRatePerYear setting. In this setting, incentive tokens (i.e. ARB) would be transferred directly to the vault and some emissionRate and endTime would be specified. Vault users would claim their share of these incentives over time.
@T-Woodward @jeffywu

**Comment by T-Woodward** [comment]
We would use whichever pool type matches the pool. The reward mode is irrelevant. For example, if we are putting extra rewards on a Balancer/Aura pool via the emission rate mode, the pool type would be an Aura pool. If we did want to use this vault rewarder on a vault where the pool was not one of those pool types, we would have a problem. So yes, this does not work for all scenarios out of the box, but I don't think that constitutes a vulnerability

**Comment by 0502lian** [comment]
> We would use whichever pool type matches the pool. The reward mode is irrelevant. For example, if we are putting extra rewards on a Balancer/Aura pool via the emission rate mode, the pool type would be an Aura pool. If we did want to use this vault rewarder on a vault where the pool was not one of those pool types, we would have a problem. So yes, this does not work for all scenarios out of the box, but I don't think that constitutes a vulnerability

According to my understanding, the current code cannot handle the standalone Emission Rate Mode, correct?

And according to the documentation, Emission Rate Mode should be an independent reward mode, not dependent on Account Claim Mode.

**Comment by WangSecurity** [comment]
@T-Woodward as I understand you mean that even in Emission Rate Mode, you're still planning to use a specific reward pool type, correct?

**Comment by T-Woodward** [comment]
That's correct @WangSecurity

**Comment by 0502lian** [comment]
**Due to the lack of implementation for the independent Emission Rate Mode reward function, according to Sherlock’s rules, this should be considered a medium severity issue.**

https://docs.sherlock.xyz/audits/judging/judging
The protocol team can use the README (and only the README) to define language that indicates the codebase's restrictions and/or expected functionality. Issues that break these statements, irrespective of whether the impact is low/unknown, will be assigned Medium severity. High severity will be applied only if the issue falls into the High severity category in the judging guidelines.

Example: The README states "Admin can only call XYZ function once" but the code allows the Admin to call XYZ function twice; this is a valid Medium

**Comment by WangSecurity** [comment]
@0502lian excuse me if I miss something, but I don't see which statement from the README is broken here, could help me with that?

**Comment by 0502lian** [comment]
> @0502lian excuse me if I miss something, but I don't see which statement from the README is broken here, could help me with that?

In Readme, they list their doc  that indicates the codebase's restrictions and/or expected functionality.
https://docs.google.com/document/d/1gWFOt9m3fwFGMHk5TxPOf8KkY1ONqY9N1wPKT02ZJfI/edit

**In the doc They explicitly stated the  support three types of reward distribution modes.  You can check that.**

“The VaultRewarderLib is meant to be an extension that allows for more flexibility when dealing with incentives. There are three potential treatments for incentive tokens:

1 Automatic Reinvest: this is the default mode for an incentive tokens. Tokens are claimed onto the vault and a whitelisted REWARDER_ROLE will trade the incentives and increase the total LP tokens held by all users in the vault. If an incentive token is not explicitly whitelisted by updateRewardToken then it will be in Automatic Reinvest mode.
2 Account Claim: governance will call updateRewardToken and whitelist an incentive token with an emissionRatePerYear set to zero. Once the incentive token is listed it cannot be removed and will no longer be in Automatic Reinvest mode. From this point forward, whenever an account enters, exits or manually claims rewards an accumulator will be used to determine how many incentive tokens an account has a claim on. There is a setting in StrategyVaultSettings called “forceClaimAfter” which can be used to limit the frequency of claims on mainnet where gas costs can be significant. An account can always bypass this check by calling claimRewardTokens prior to exiting.
3 Emission Rate: in addition to allowing claimed incentives from booster protocols, the vault may also be incentivized directly using the emissionRatePerYear setting. In this setting, incentive tokens (i.e. ARB) would be transferred directly to the vault and some emissionRate and endTime would be specified. Vault users would claim their share of these incentives over time.”


According to the sponsor’s explanation, even in Only Emission Rate mode, it must be set as the Account Claim mode’s reward pool type and reward pool address.

Although this is barely workable, it feels strange because Only Emission Rate mode does not require the call to IConvexRewardPool(r.rewardPool).getReward().

This will result in unnecessary gas costs for users, especially on the Ethereum mainnet.

If the DOC stated that Only Emission Rate mode is attached to Account Claim mode, rather than being one of three independent modes as it is currently described, I would not have submitted this issue.


```javascript
enum RewardPoolType {
    _UNUSED,
    AURA,
    CONVEX_MAINNET,
    CONVEX_ARBITRUM
}

 function _executeClaim(RewardPoolStorage memory r) internal {
        if (r.poolType == RewardPoolType.AURA) {
            require(IAuraRewardPool(r.rewardPool).getReward(address(this), true));
        } else if (r.poolType == RewardPoolType.CONVEX_MAINNET) {
            require(IConvexRewardPool(r.rewardPool).getReward(address(this), true));
        } else if (r.poolType == RewardPoolType.CONVEX_ARBITRUM) {
            IConvexRewardPoolArbitrum(r.rewardPool).getReward(address(this));
        } else {
         revert();
        }
    }
```

**Comment by WangSecurity** [comment]
Then the rule about broken statements doesn't apply here, since the statement is in the protocol documentation. Planning to reject the escalation and leave the issue as it is, since even with Emission Rate Mode, there will be a reward pool type.

**Comment by 0502lian** [comment]
> since even with Emission Rate Mode, there will be a reward pool type.

Yes, but It should have its own reward pool type(not in code now), rather than forcibly using the reward pool type and handling logic of Account Claim mode’s.  That’s exactly what I meant.

This is what the sponsor said.
>If we did want to use this vault rewarder on a vault where the pool was not one of those pool types, we would have a problem. So yes, this does not work for all scenarios out of the box, 

 However, Only Emission Rate mode is just not one of those pool types.

**Comment by WangSecurity** [comment]
My decision remains the same, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0502lian](https://github.com/sherlock-audit/2024-06-leveraged-vaults-judging/issues/45/#issuecomment-2226687514): rejected
