### ISSUE TITLE
Ironsidesec - No deadline protection from MEV

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-leveraged-vaults-judging#79]
Ironsidesec

Medium

# No deadline protection from MEV

## Summary
The protocol uses `block.timestamp` as the deadline argument while executing swaps (`_executeTrade`), which completely defeats the purpose of using a deadline.

This issue is on 
1. [BaseStakingVault._redeemFromNotional](https://github.com/sherlock-audit/2024-06-leveraged-vaults/blob/14d3eaf0445c251c52c86ce88a84a3f5b9dfad94/leveraged-vaults-private/contracts/vaults/staking/BaseStakingVault.sol#L170)
2. [BaseStakingVault._executeInstantRedemption](https://github.com/sherlock-audit/2024-06-leveraged-vaults/blob/14d3eaf0445c251c52c86ce88a84a3f5b9dfad94/leveraged-vaults-private/contracts/vaults/staking/BaseStakingVault.sol#L197)
3. [EthenaVault._stakeTokens](https://github.com/sherlock-audit/2024-06-leveraged-vaults/blob/14d3eaf0445c251c52c86ce88a84a3f5b9dfad94/leveraged-vaults-private/contracts/vaults/staking/EthenaVault.sol#L65)
4. [PendlePrincipalToken._stakeTokens](https://github.com/sherlock-audit/2024-06-leveraged-vaults/blob/14d3eaf0445c251c52c86ce88a84a3f5b9dfad94/leveraged-vaults-private/contracts/vaults/staking/protocols/PendlePrincipalToken.sol#L86)
5. [PendlePrincipalToken._executeInstantRedemption](https://github.com/sherlock-audit/2024-06-leveraged-vaults/blob/14d3eaf0445c251c52c86ce88a84a3f5b9dfad94/leveraged-vaults-private/contracts/vaults/staking/protocols/PendlePrincipalToken.sol#L155)
6. [Ethena._sellStakedUSDe](https://github.com/sherlock-audit/2024-06-leveraged-vaults/blob/14d3eaf0445c251c52c86ce88a84a3f5b9dfad94/leveraged-vaults-private/contracts/vaults/staking/protocols/Ethena.sol#L138-L158)

## Vulnerability Detail
Using block.timestamp as the deadline is effectively a no-operation that has no effect nor protection. Since `block.timestamp` will take the timestamp value when the transaction gets mined, the check will end up comparing block.timestamp against the same value, i.e. block.timestamp <= block.timestamp.

Passing block.timestamp as the expiry/deadline of an operation does not mean "require immediate execution" - it means "whatever block this transaction appears in, I'm comfortable with that block's timestamp". Providing this value means that a malicious miner can hold the transaction for as long as they like (think the flashbots mempool for bundling transactions), which may be until they are able to cause the transaction to incur the maximum amount of slippage allowed by the slippage parameter, or until conditions become unfavorable enough that other orders, e.g. liquidations, are triggered. Timestamps should be chosen off-chain, and should be specified by the caller to avoid unnecessary MEV.

## Impact
No MEV protection on using `block.timestamp` as deadline. Failure to provide a proper deadline value enables pending transactions to be maliciously executed at a later point. Transactions that provide an insufficient amount of gas such that they are not mined within a reasonable amount of time, can be picked by malicious actors or MEV bots and executed later in the detriment of the submitter.

See [this issue](https://github.com/code-423n4/2022-12-backed-findings/issues/64) for an excellent reference on the topic (the author runs an MEV bot).

## Code Snippet

```solidity
            Trade memory trade = Trade({
                tradeType: TradeType.EXACT_IN_SINGLE,
                sellToken: TOKEN_OUT_SY,
                buyToken: BORROW_TOKEN,
                amount: netTokenOut,
                limit: params.minPurchaseAmount,
    >>>>        deadline: block.timestamp,
                exchangeData: params.exchangeData
            });
```

## Tool used
Manual Review

## Recommendation
Add a deadline parameter to the input of functions used to execute swaps (`_executeTrade`). So that off-chain calculated deadline can be used against the MEV.

**Comment by xiaoming9090** [comment]
Escalate.

This should be a low due to the following reasons:

- As the sponsor has mentioned, users can choose to resubmit the existing transaction with a higher gas price to "burn" the current transaction instead of leaving it dangling in the mempool. A certain level of user error is required here as it requires them to submit a transaction at an extremely low price and not monitor whether the transaction has been executed in a timely manner.
- The `Trade` struct contains a `limit` parameter (see below) that acts as a slippage control and allows users to define the minimum output amount. Thus, the gain that the MEV bots can gain is subjected to the maximum slippage set by the users.

```solidity
            Trade memory trade = Trade({
                tradeType: TradeType.EXACT_IN_SINGLE,
                sellToken: TOKEN_OUT_SY,
                buyToken: BORROW_TOKEN,
                amount: netTokenOut,
   >>>>>>>>>>>> limit: params.minPurchaseAmount,
                deadline: block.timestamp,
                exchangeData: params.exchangeData
            });
```

**Comment by sherlock-admin3** [comment]
> Escalate.
> 
> This should be a low due to the following reasons:
> 
> - As the sponsor has mentioned, users can choose to resubmit the existing transaction with a higher gas price to "burn" the current transaction instead of leaving it dangling in the mempool. A certain level of user error is required here as it requires them to submit a transaction at an extremely low price and not monitor whether the transaction has been executed in a timely manner.
> - The `Trade` struct contains a `limit` parameter (see below) that acts as a slippage control and allows users to define the minimum output amount. Thus, the gain that the MEV bots can gain is subjected to the maximum slippage set by the users.
> 
> ```solidity
>             Trade memory trade = Trade({
>                 tradeType: TradeType.EXACT_IN_SINGLE,
>                 sellToken: TOKEN_OUT_SY,
>                 buyToken: BORROW_TOKEN,
>                 amount: netTokenOut,
>    >>>>>>>>>>>> limit: params.minPurchaseAmount,
>                 deadline: block.timestamp,
>                 exchangeData: params.exchangeData
>             });
> ```

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
I think medium severity is still appropriate given the Sherlock rule:

"Slippage related issues showing a definite loss of funds with a detailed explanation for the same can be considered valid high"

Also, per trust comment in the C4 [linked issue](https://github.com/code-423n4/2022-12-backed-findings/issues/64):

"On the fence between L and M. I tend to view "stealing of positive slippage" as meaningful enough to warrant M severity."

The linked issue it does look like they downgraded the severity of this issue from high to medium.

**Comment by WangSecurity** [comment]
I agree with the LSW, indeed the user is responsible for providing as much gas as they want and we should assume the users know the higher the gas they provide the faster the txn will be executed. Moreover, as correctly mentioned twice above, they can re-submit the txn with higher gas, not only that, they can "speed up" the transaction by sending additional gas to the transaction already in the mempool.

Secondly, as mentioned by the LSW again, all the mentioned functions have the slippage protection applied. Hence, even if the transaction spends too much time in the mempool and the token price changes too much, the transaction would just revert. So there is no loss of funds here (loss of funds limited by the slippage is considered acceptable). Thus, the rule "Slippage related issues showing a definite loss of funds with a detailed explanation for the same can be considered valid high" cannot apply here.

I agree it is low severity. Planning to accept the escalation and invalidate the report.

**Comment by NishithPat** [comment]
This issue is also explained well here - https://solodit.xyz/issues/m-38-missing-transaction-expiration-check-result-in-reward-tokens-selling-at-a-lower-price-sherlock-derby-derby-git

If the acceptable slippage is set to 5%, and let's say that if the transaction gets executed immediately then it would only experience 1% slippage (what the user would've wanted). But, since there is no deadline given and any deadline (block.timestamp) is acceptable, then at a later stage when the transaction finally gets executed it experiences a 4.5% slippage (due to change in market conditions) and does not revert. Then isn't there a loss of funds here? There certainly is. Hence, Trust had given the issue linked above a medium severity. And according to Sherlock's rules, this fact alone (loss of funds) should warrant this issue a medium severity.

Also, please read the linked issue. It talks about this issue happening when the gas prices become quite high when there's a lot of traffic on-chain. The increased gas price situation counters the LSW's 1st point. When prices are very high, then it is simply not viable for users to resubmit the transaction at a higher gas price, or "speeding up" the transaction by sending additional gas. As this issue is mostly going to happen in high gas price situations, resubmitting the transaction is not a solution. This will decrease the profitability of the original transaction and most users will not be willing to do so. 

>certain level of user error is required here as it requires them to submit a transaction at an extremely low price

This does need to be a user error. Market conditions can also cause this issue to happen as explained above.

"Slippage related issues showing a definite loss of funds with a detailed explanation for the same can be considered valid high" does apply here.

Please reconsider the issue.

**Comment by IronsideSec** [comment]
@WangSecurity partially disagreed at 
>the user is responsible for providing as much gas as they want and we should assume the users know the higher the gas they provide the faster the txn will be executed

>all the mentioned functions have the slippage protection applied. Hence, even if the transaction spends too much time in the mempool and the token price changes too much, the transaction would just revert. So there is no loss of funds here (loss of funds limited by the slippage is considered acceptable)

This is true only for price dips, but if price surges, the user expects to be executed at 0.5% slippage at a surged price. 
User can define 30 sec deadline for current accepted price. And beyond 30sec, the swap should not be performed. That is the feature missed here and MEV is extracted, so its definitely a loss of funds, but still user has chance to cancel or update transaction and the low likelihood of wrong gas estimates/sudden price or gas surge/ not all wallets are rabby/ cancelling flashbots transactions are longer (atleast 15 sec). So this makes it a medium impact.

Users submit transactions based on % of amounts as slippage. ex: 0.5%.  They do not enter exact numbers as minimum amount. As a user I am okay with 0.5% slippage at $3500/eth and `minAmount` = 3,482.5
Imagine a sudden 2% rise to $3570/eth (ex: trump got shot, so pump) and the new slippage amount is 3,552.15. So now, as a user I want to be executed at this price but, its actually done at = 3,482.5. Good MEV extraction at these times. Deadline is important for these kind of users.

**Comment by DenTonylifer** [comment]
>Users submit transactions based on % of amounts as slippage. ex: 0.5%. They do not enter exact numbers as minimum amount.

They do enter exact numbers as minimum amount:
```solidity
function redeemFromNotional(
        //...
>>>     bytes calldata data                                  
    ) external onlyNotional returns (uint256 transferToReceiver) {
```
```solidity
RedeemParams memory params = abi.decode(data, (RedeemParams));
//...
limit: params.minPurchaseAmount,
```
```solidity
 struct RedeemParams {
>>>     uint256 minPurchaseAmount;
        uint16 dexId;
        bytes exchangeData;
    }
```
Slippage is user-defined ```Minimum purchase amount of the underlying token```, but not minimum percentage of the current floating price.

**Comment by NishithPat** [comment]
What I am trying to say is that if you wanted to swap input tokens and wanted to receive 100 output tokens in return, with 5% slippage you would want to input 95 as `minPurchaseAmount`. And, if the transaction was to immediately execute (the user experiences 1% slippage) and would get 99 tokens (what the user expects). But, since the transaction is delayed and market conditions change, the user experiences more slippage (let's say 4%), and they receive 96 tokens, instead of 99. This is a loss to the user in these conditions.

>Slippage is user-defined Minimum purchase amount of the underlying token, but not minimum percentage of the current floating price.

If you would perform a swap transaction on uniswap, you would take the current price into account to calculate how many tokens you want to receive. Also, in the issue I linked earlier, there's this line:

>Since the value of amountOutMinimum was calculated based on an outdated reward token price which is now lower than the current price, the swapping is sandwiched by a MEV bot

I suggest you read this issue - https://solodit.xyz/issues/m-38-missing-transaction-expiration-check-result-in-reward-tokens-selling-at-a-lower-price-sherlock-derby-derby-git

Also, I know that Sherlock does not consider historical judging anymore. But, issues like these have always been judged as medium. The underlying logic behind these issues has not changed, so why should the judging for this issue change?

**Comment by IronsideSec** [comment]
@DenTonylifer 
> > Users submit transactions based on % of amounts as slippage. ex: 0.5%. They do not enter exact numbers as minimum amount.
> 
> They do enter exact numbers as minimum amount:

I am talking from user UI / UX point of view. Users enter comfortable %.  Backend submits the `minAmount`.

**Comment by WangSecurity** [comment]
I see the points from Watsons, that if there's a deadline you can get slightly better outcome, but still, the "loss of funds" in any case is restricted by user input slippage. The loss limited by the slippage decided by the user is considered an acceptable loss.

Hence, the decision remains the same, planning to accept the escalation and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [xiaoming9090](https://github.com/sherlock-audit/2024-06-leveraged-vaults-judging/issues/79/#issuecomment-2227183184): accepted
